const mongoose = require('mongoose')
// const validator = require('validator')


const user_wallet = new mongoose.Schema({
    user_Id:{
        type: String,
        required:true
    },
    main_wallet:{
       name:{
        type:String,
        default:"Main Wallet"
       },
       wallet_type:{
        type:String,
        default:"wallet"
       },
       count_in_wallet:{
        type:String,
        default:null
       },
       wallet_status:{
        type:Number,
        default:1
       },
       value:{
        type:Number,
        default:0
       }
    },
    withdrawable:{
        name:{
         type:String,
         default:"withdrawable Amount"
        },
        wallet_type:{
         type:String,
         default:"wallet"
        },
        count_in_wallet:{
         type:String,
         default:null
        },
        wallet_status:{
         type:Number,
         default:1
        },
        value:{
         type:Number,
         default:0
        }
     },
     total_withdrawal:{
        name:{
         type:String,
         default:"Total Withdrawal"
        },
        wallet_type:{
         type:String,
         default:"wallet"
        },
        count_in_wallet:{
         type:String,
         default:null
        },
        wallet_status:{
         type:Number,
         default:1
        },
        value:{
         type:Number,
         default:0
        }
     },
     total_payout:{
        name:{
         type:String,
         default:"Total Payout"
        },
        wallet_type:{
         type:String,
         default:"wallet"
        },
        count_in_wallet:{
         type:String,
         default:null
        },
        wallet_status:{
         type:Number,
         default:1
        },
        value:{
         type:Number,
         default:0
        }
     },
    fund_wallet:{
        name:{
         type:String,
         default:"Fund Wallet"
        },
        wallet_type:{
         type:String,
         default:"wallet"
        },
        count_in_wallet:{
         type:String,
         default:null
        },
        wallet_status:{
         type:Number,
         default:1
        },
        value:{
         type:Number,
         default:0
        }
     },
     level_income:{
        name:{
         type:String,
         default:"Level Income"
        },
        wallet_type:{
         type:String,
         default:"income"
        },
        count_in_wallet:{
         type:String,
         default:"main_wallet"
        },
        wallet_status:{
         type:Number,
         default:1
        },
        value:{
         type:Number,
         default:0
        }
     },
     direct_income:{
        name:{
         type:String,
         default:"Direct Income"
        },
        wallet_type:{
         type:String,
         default:"income"
        },
        count_in_wallet:{
         type:String,
         default:"main_wallet"
        },
        wallet_status:{
         type:Number,
         default:1
        },
        value:{
         type:Number,
         default:0
        }
     },
     binary_income:{
        name:{
         type:String,
         default:"Binary Income"
        },
        wallet_type:{
         type:String,
         default:"income"
        },
        count_in_wallet:{
         type:String,
         default:"main_wallet"
        },
        wallet_status:{
         type:Number,
         default:0
        },
        value:{
         type:Number,
         default:0
        }
     },
     single_leg_income:{
        name:{
         type:String,
         default:"Single Leg Income"
        },
        wallet_type:{
         type:String,
         default:"income"
        },
        count_in_wallet:{
         type:String,
         default:"main_wallet"
        },
        wallet_status:{
         type:Number,
         default:0
        },
        value:{
         type:Number,
         default:0
        }
     },
     matrix_income:{
        name:{
         type:String,
         default:"Matrix Income"
        },
        wallet_type:{
         type:String,
         default:"income"
        },
        count_in_wallet:{
         type:String,
         default:"main_wallet"
        },
        wallet_status:{
         type:Number,
         default:1
        },
        value:{
         type:Number,
         default:0
        }
     },
     roi_income:{
        name:{
         type:String,
         default:"Roi Income"
        },
        wallet_type:{
         type:String,
         default:"income"
        },
        count_in_wallet:{
         type:String,
         default:"main_wallet"
        },
        wallet_status:{
         type:Number,
         default:1
        },
        value:{
         type:Number,
         default:0
        }
     },
     roi_level_income:{
        name:{
         type:String,
         default:"Roi Level Income"
        },
        wallet_type:{
         type:String,
         default:"income"
        },
        count_in_wallet:{
         type:String,
         default:"main_wallet"
        },
        wallet_status:{
         type:Number,
         default:1
        },
        value:{
         type:Number,
         default:0
        }
     },
})
const userWallet = new mongoose.model('user_wallet', user_wallet)
module.exports = userWallet;